# Generated by Django 4.2.10 on 2025-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumber1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=1)),
                ('prefix', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentNumber',
        ),
    ]
